---
title       : Tradosin perusteet
author      : Juho Härme
job         : tohtorikoulutettava / käännöstiede venäjä
framework   : revealjs        # {io2012, html5slides, shower, dzslides, ...}
revealjs    : {theme: serif, transition: linear, center: "false"}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : mathjax            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
logo        : slidify_logo.png

---

<style>
.reveal h2{
    padding-bottom: 20px;
}

.reveal p { text-align: left;
font-size: 75%;
font-family:
}

.reveal ul{
font-size: 80%;
width:70%;
}

p.fragment{
    margin-top: 3%;
    margin-bottom: 3%;
    padding: 3px;
    padding-left: 10px;
    border-left: 2px solid black;
    /* border-right: 2px solid black; */
    color: firebrick;
}

.reveal a:not(.image) {
text-decoration:underline;
}

.coldiv {width:47%;float:left;}
.coldiv2 {float:left;width:30%;}


.rowdiv {width:100%;clear:left;}

.reveal section img { background:none; border:none; box-shadow:none; }

li.fragment{
font-size:80%;
}

ul,li,li.fragment{
font-size:80%;
}

.gr1{
border-radius:3px;
background:antiquewhite;
}
.gr2{
border-radius:3px;
background:aquamarine;
}

</style>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

## Tradosin perusteet 3

#### Juho Härme / 25.9.2015


--- .class &vertical

## Oppitunnin rakenne


--- .class &vertical

#### 1. Itsenäinen tehtävä

.fragment Ajatuksia itsenäisestä tehtävästä

.fragment Asioita, joita pyydettiin kerrattavaksi

***
<!--
Otetaan jokin nettisivu käännettäväksi tunnin alussa
- Voidaan käsitellä tägejä + samalla katsoa kaikkea tätä

Muista korostaa
-->

***

#### Projektin luominen ja muistit

> - Miten tiedostokansio määritellään projektin alussa?
> - Miten käännösmuisti luodaan?
> - Pitikö muistia lisätessä valita jostain erikseen, päivitetäänkö sitä vai ei
> - Miten muistin ja tiedoston sijainti tarkistetaan?
> - Muisti verkkolevyllä

***

#### Muotoilut, segmentointi

> - Jos lähtötekstin formatoinneissa näyttää olevan jotain vikaa (kuten oli
   hyperlinkki isomman tekstipätkän kuin nettiosoitteen ympärillä), voiko sen
   korjata käännökseen?
> - Lähtötekstin palaset ovat parissa kohdassa Tradosin jaottelun jäljiltä ihan sekaisin


--- .class &vertical

#### 2. Muotoiludata

.fragment Tägit, kuvat

.fragment Muotoiludatan näkyminen käännöseditorissa


--- .class &vertical


#### 3.  Kohti projektitehtävää

.fragment Verkkomuistit

.fragment Mitä haluat tietää ennen projektitehtäviä?

.fragment Jos aikaa jää: mitä ovat termipankit

<script>
$('ul.incremental li').addClass('fragment')//note to anyone reading this code, you may need to change to ul from ol depending on ordered vs unordered list
</script>
