---
title       : Tradosin perusteet
author      : Juho Härme
job         : tohtorikoulutettava / käännöstiede venäjä
framework   : revealjs        # {io2012, html5slides, shower, dzslides, ...}
revealjs    : {theme: serif, transition: linear, center: "false"}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : mathjax            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
logo        : slidify_logo.png

---

<style>
.reveal h2{
    padding-bottom: 20px;
}

p { text-align: left;
font-size: 12;

}

.reveal a:not(.image) {
text-decoration:underline;
}

.coldiv {width:47%;float:left;}
.coldiv2 {float:left;width:30%;}


.rowdiv {width:100%;clear:left;}

.reveal section img { background:none; border:none; box-shadow:none; }

li.fragment{
font-size:80%;
}

ul,li,li.fragment{
font-size:80%;
}

.gr1{
border-radius:3px;
background:antiquewhite;
}
.gr2{
border-radius:3px;
background:aquamarine;
}

</style>

## Tradosin perusteet 1

#### Juho Härme / 18.9.2015


--- .class &vertical

## Oppimistavoitteita

<!--Linkit/sivunumerot tähän minioppaisiin kustakin asiasta! --> 

***

#### Perustaitoja

<ul>

<ul class='fragment gr2'>
<li style='font-size:75%;'> Oleellisen erottaminen käyttöliittymästä
<li style='font-size:75%;'> Käännösmuistin hyödyntäminen
</ul>
<br>
<ul class='fragment gr1'>
<li style='font-size:75%;'> Yksittäisen tiedoston kääntäminen
<li style='font-size:75%;'> Paketin kääntäminen
<li style='font-size:75%;'> Erilaisten tiedostomuotojen hallitseminen
<li style='font-size:75%;'> Projektin luominen
</ul>
<br>
<ul class='fragment gr2'>
<li style='font-size:75%;'> Käännöksen viimeistely ja eksportointi
<li style='font-size:75%;'> Käännöksen palauttaminen asiakkaalle / toimistolle
</ul>

</ul>

***

#### Tärkeitä toimintoja

<ul>
<ul class='fragment gr1'>
<li style='font-size:75%;'> Konkordanssihaku
<li style='font-size:75%;'> Muistiyksikön muokkaaminen
<li style='font-size:75%;'> Esikatselu
</ul>
<br>
<ul class='fragment gr2'>
<li style='font-size:75%;'> Tägien ja muotoilujen syöttäminen
<li style='font-size:75%;'> Lähdesegmentin kopioiminen
</ul>
</ul>

***

#### Hyödyllisiä lisätaitoja

<ul>
<li style='font-size:75%;'> Käännösmuistin eksportoiminen
<li style='font-size:75%;'> Termipankin käyttö ja rakentaminen
<li style='font-size:75%;'> Tekstien kohdistaminen
</ul>

--- 

### Ensimmäisellä tunnilla:

<br>
<ul>
<li style='font-size:75%;' class='fragment'> Käännösharjoitus 1: yksittäinen tiedosto, tyhjä muisti
<li style='font-size:75%;' class='fragment'> Käännösharjoitus 2: yksittäinen tiedosto, valmis muisti
<li style='font-size:75%;' class='fragment'> Käyttöliittymään tutustumista
</ul>


---

### Toisella tunnilla

<br>
<ul>
<li style='font-size:75%;' class='fragment'> Projektit ja paketit
<li style='font-size:75%;' class='fragment'> Muisti serverillä
</ul>

---

### Itsenäiset harjoituskerrat


