---
title       : Tradosin perusteet
author      : Juho Härme
job         : tohtorikoulutettava / käännöstiede venäjä
framework   : revealjs        # {io2012, html5slides, shower, dzslides, ...}
revealjs    : {theme: serif, transition: linear, center: "false"}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : mathjax            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
logo        : slidify_logo.png

---

<style>
.reveal h2{
    padding-bottom: 20px;
}

.reveal p { text-align: left;
font-size: 75%;
font-family:
}

.reveal a:not(.image) {
text-decoration:underline;
}

.coldiv {width:47%;float:left;}
.coldiv2 {float:left;width:30%;}


.rowdiv {width:100%;clear:left;}

.reveal section img { background:none; border:none; box-shadow:none; }

li.fragment{
font-size:80%;
}

ul,li,li.fragment{
font-size:80%;
}

.gr1{
border-radius:3px;
background:antiquewhite;
}
.gr2{
border-radius:3px;
background:aquamarine;
}

</style>

## Tradosin perusteet 2

#### Juho Härme / 25.9.2015


--- .class &vertical

## Oppitunnin rakenne


--- .class &vertical

### 1. Kertaus

.fragment yksittäisen tiedostoparin kääntäminen 

.fragment simppeli projekti


***

1. Hae moodlesta kolme tiedostoa *yhteinen harjoitus* -kansiosta

2. Valitse yksi niistä (esim. "Tilat") ja käännä se "Translate single file pair" -toiminnon avulla

   * Huom! Luo uusi käännösmuisti tätä varten

3. Luo uusi *projekti* ja liitä siihen kaksi muuta tekstiä + äsken luomasi käännösmuisti


--- .class &vertical

### 2.  Tradosin toimintoja

.fragment Konkordanssi

.fragment Suodattimet

.fragment Lähdesegmentin kopioiminen

.fragment Käännösmuistin muokkaaminen

--- .class &vertical

### 3. Mitä tapahtuu, kun käännös on valmis?

.fragment Kieliasun tarkistus

.fragment Verifiointi

.fragment Viimeistely (Finalize-toiminto)

.fragment Millaisia tiedostoja Trados tuottaa ja minne?

--- .class &vertical

### 4. Itsenäinen harjoitus

.fragment Muisti verkkolevyllä

.fragment tmx:nä jaettu muisti

.fragment pdf lähdetiedostona

***


- Lataa kaikki oman työkielesi tiedostot koneellesi moodlen *itsenäinen harjoitus* -kansiosta
- Luo uusi projekti Tradosissa

Huom! Tallenna projekti omaan kansioosi x-levylle

- Liitä projektiin muistit:
    - verkkomuisti osoitteesta t:/trados/kaannostyopaja2015-2016/itsenainen_harjoitus
    - erillinen tmx-muisti (esim. bb_En-Fi.tmx):
            * Anna Tradosin konvertoida muisti (valitse quick import)

Vaihtakaa parin kanssa ja anna parin tehdä sama
